Second project code review
pastorp3/SingUpClone pull request #2
Opened 2020-07-14 19:19 UTC by pastorp3

our project has the next requirements:

- Add linterns file 

- HTML and CSS structure

-designed as the original page

- We use only HTML and css

2020-07-14 19:45 UTC, tirthajyoti-ghosh requested changes
# Changes required 🛑 

## What a remarkable project you have built 💯! This is impressive 🤩👌🧨!

### But in order to get it approved, we need to work on some changes. Let's see...

- Great job adding the linter config files. But you have a typo in your folder name. Right now its `.githubworkflows` but it should be `.github/workflows`. The `workflows` folder should be inside `.github` folder. The linter config file should be inside the `workflows` folder. Here are the instructions: https://github.com/microverseinc/linters-config/tree/master/html-css

- Files not related to the project should not be committed. Please remove this `.rar` file from your repository.

![image](https://user-images.githubusercontent.com/57726348/87468679-af040a80-c637-11ea-9982-e82906a164e6.png)

- There are a lot of errors and warnings in your HTML file. Please visit https://validator.w3.org/#validate_by_input, paste your HTML code, go through each of the errors and warnings and fix them

![image](https://user-images.githubusercontent.com/57726348/87468937-1752ec00-c638-11ea-81f4-6c5570683dc4.png)

- You have one invalid CSS property. Check the comment.

2020-07-14 19:46 UTC, tirthajyoti-ghosh commented on css/main.css
> +    float: center;
`float` can only have `left` or `right` as its value. `center` is not a valid `float` value.

2020-07-14 19:50 UTC, tirthajyoti-ghosh requested changes
- Remember to fix the typo in your github workflows folder name. Otherwise, github actions won't work.
- Be sure to remove any irrelevant files from your repository.
- Please make sure to fix all the errors and warnings in your HTML code.


Your project looks absolutely fantastic. Just make these changes and apply for another code review.

Happy coding 👨‍💻

2020-07-14 21:16 UTC, pastorp3 commented
- We change .github folder and linters now it's working

- We delete the not related file

- We change css style in body

- We already fix all of the error in HTML validation

2020-07-15 03:03 UTC, voscarmv requested changes
# Nice work so far, team. 👍 
- Well-structured `README` file.
- Good, descriptive, Pull Request message.

## However, there are some changes required 👀 🧰 🔨 🔧 
- The top right corner button is overflowing to the right side of the creen. Even when zooming in and out, the button still overflows to the right. Kindly fix this.
![image](https://user-images.githubusercontent.com/2739245/87497854-0e542180-c61c-11ea-8136-6dd5488c6c26.png)
- The product names are only images. The products below the INTUIT logo are supposed to be composed of the logo followed by text, not just an image. Kindly fix this as well.
![image](https://user-images.githubusercontent.com/2739245/87497978-64c16000-c61c-11ea-92ab-5d5bda28d006.png)
- Also, if possible, fix the INTUIT logo so that it does not look stretched. It should look similar to the original:
![image](https://user-images.githubusercontent.com/2739245/87498042-80c50180-c61c-11ea-9ceb-52a71e77a573.png)
- Use the `<main>` semantic tag to denote the main section of your `index.html`.

**[OPTIONAL]**
- Please improve your commit messages in the future. Messages such as `edit html` or `html design` say very little about what was done. Make a short summary of the specific parts of the project that you worked on, rather than generic descriptions.

### Questions or comments? Reach me on [Twitter](https://twitter.com/voscarmv) or [LinkedIn](https://linkedin.com/in/oscar-mier) 🧑‍💻🗨️🧑‍💻 
# Happy Hacking! 🧠 ⌨️ 🖱️ 🖥️

2020-07-15 03:03 UTC, voscarmv commented on index.html
> +<!-- Start main section-->
Rather than only indicating the main section with an HTML comment, please use a proper `<main>` semantic tag here.

2020-07-15 17:25 UTC, pastorp3 commented
- icon change to icon and text

- add main tag to HTML

-gray log of intuit

- fix nav bar

2020-07-15 17:57 UTC, expjazz approved these changes
## Status: Project Approved :green_circle: 

### Great work team. The page looks quite good and you implemented all that was requested by my colleagues above.  :clap: 

If you want to make the projects even better, please consider some optional changes below:
- [optional] Use the same background color as the original.
- [optional] Use less id's for the next projects because they have to be unique and that is hard to manage.

Good Luck and Happy Coding :pray:

_P.S. If you have any questions about my review or need help, you can message me on slack (@ Expedito Andrade).:smile:_

2020-07-15 18:41 UTC, janis-jenny commented
Second project code review:

This is our last changes in the second project before I merge it:

-Icons changed to icons and text
-Changed color of Intuit logo to grey
-Added more margin to the form 
-Changed the navbar to align its items and to have the same font
-Added main tag to HTML.

2020-07-15 18:45 UTC, merged